2018-10-17 21:34:43,846 INFO: Microblog startup [in G:\Masters\Study\WebProgramming\practice\microblog\app\__init__.py:43]
2018-10-24 20:27:00,402 INFO: Microblog startup [in G:\Masters\Study\WebProgramming\practice\microblog\app\__init__.py:43]
2018-10-24 20:42:51,754 INFO: Microblog startup [in G:\Masters\Study\WebProgramming\practice\microblog\app\__init__.py:43]
2018-10-24 20:43:07,623 INFO: Microblog startup [in G:\Masters\Study\WebProgramming\practice\microblog\app\__init__.py:43]
2018-10-24 20:43:53,374 INFO: Microblog startup [in G:\Masters\Study\WebProgramming\practice\microblog\app\__init__.py:43]
2018-10-24 20:55:44,136 INFO: Microblog startup [in G:\Masters\Study\WebProgramming\practice\microblog\app\__init__.py:43]
2018-10-24 20:56:03,066 ERROR: Exception on /index [GET] [in g:\masters\study\webprogramming\practice\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "g:\masters\study\webprogramming\practice\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "g:\masters\study\webprogramming\practice\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "g:\masters\study\webprogramming\practice\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "g:\masters\study\webprogramming\practice\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "g:\masters\study\webprogramming\practice\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "g:\masters\study\webprogramming\practice\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "g:\masters\study\webprogramming\practice\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "G:\Masters\Study\WebProgramming\practice\microblog\app\routes.py", line 43, in index
    form = PostForm()
NameError: name 'PostForm' is not defined
2018-10-24 20:57:39,504 INFO: Microblog startup [in G:\Masters\Study\WebProgramming\practice\microblog\app\__init__.py:43]
2018-10-24 21:06:44,652 INFO: Microblog startup [in G:\Masters\Study\WebProgramming\practice\microblog\app\__init__.py:43]
2018-10-24 21:30:23,086 INFO: Microblog startup [in G:\Masters\Study\WebProgramming\practice\microblog\app\__init__.py:43]
2018-10-24 21:31:13,276 INFO: Microblog startup [in G:\Masters\Study\WebProgramming\practice\microblog\app\__init__.py:43]
2018-10-24 21:38:59,821 INFO: Microblog startup [in G:\Masters\Study\WebProgramming\practice\microblog\app\__init__.py:43]
2018-12-11 01:08:16,960 INFO: Microblog startup [in G:\Masters\Study\WebProgramming\practice\microblog\app\__init__.py:47]
2018-12-11 01:16:30,602 INFO: Microblog startup [in G:\Masters\Study\WebProgramming\practice\microblog\app\__init__.py:47]
2018-12-11 02:29:13,401 INFO: Microblog startup [in G:\Masters\Study\WebProgramming\practice\microblog\app\__init__.py:47]
2018-12-11 02:29:33,958 ERROR: Exception on /login [GET] [in g:\masters\study\webprogramming\practice\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "g:\masters\study\webprogramming\practice\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "g:\masters\study\webprogramming\practice\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "g:\masters\study\webprogramming\practice\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "g:\masters\study\webprogramming\practice\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "g:\masters\study\webprogramming\practice\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "g:\masters\study\webprogramming\practice\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "G:\Masters\Study\WebProgramming\practice\microblog\app\routes.py", line 94, in login
    return render_template('login.html', title='Sign In', form=form)
  File "g:\masters\study\webprogramming\practice\venv\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "g:\masters\study\webprogramming\practice\venv\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "g:\masters\study\webprogramming\practice\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "g:\masters\study\webprogramming\practice\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "g:\masters\study\webprogramming\practice\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "g:\masters\study\webprogramming\practice\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "G:\Masters\Study\WebProgramming\practice\microblog\app\templates\base.html", line 32, in template
    {% block content %}{% endblock %}
  File "g:\masters\study\webprogramming\practice\venv\lib\site-packages\jinja2\environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "G:\Masters\Study\WebProgramming\practice\microblog\app\templates\login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "g:\masters\study\webprogramming\practice\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "g:\masters\study\webprogramming\practice\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "G:\Masters\Study\WebProgramming\practice\microblog\app\templates\base.html", line 32, in template
    {% block content %}{% endblock %}
  File "g:\masters\study\webprogramming\practice\venv\lib\site-packages\jinja2\environment.py", line 543, in _generate
    optimized=self.optimized)
  File "g:\masters\study\webprogramming\practice\venv\lib\site-packages\jinja2\compiler.py", line 82, in generate
    generator.visit(node)
  File "g:\masters\study\webprogramming\practice\venv\lib\site-packages\jinja2\visitor.py", line 38, in visit
    return f(node, *args, **kwargs)
  File "g:\masters\study\webprogramming\practice\venv\lib\site-packages\jinja2\compiler.py", line 718, in visit_Template
    self.fail('block %r defined twice' % block.name, block.lineno)
  File "g:\masters\study\webprogramming\practice\venv\lib\site-packages\jinja2\compiler.py", line 315, in fail
    raise TemplateAssertionError(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateAssertionError: block 'content' defined twice
